server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Optional: proxy backend requests if needed, but we can do that more cleanly with env vars in React
    # location /api {
    #     proxy_pass http://backend:8000;
    # }
}
